#!/bin/bash
# Skript väljastab aastaaja vastavalt sisestatud kuu numbrile

read -p "Sisesta kuu number: " kuu

if test "$kuu" -eq 12 -o "$kuu" -eq 1 -o "$kuu" -eq 2 2>/dev/null; then
    echo "Praegu on talv"
elif test "$kuu" -ge 3 -a "$kuu" -le 5 2>/dev/null; then
    echo "Praegu on kevad"
elif test "$kuu" -ge 6 -a "$kuu" -le 8 2>/dev/null; then
    echo "Praegu on suvi"
elif test "$kuu" -ge 9 -a "$kuu" -le 11 2>/dev/null; then
    echo "Praegu on sügis"
else
    echo "Viga: Kuu number peab olema vahemikus 1-12!"
fi
